### ISSUE TITLE
Questions about implementations and the paper

### ISSUE THREAD

**Issue by hjf1997** [frigategnn/Frigate#2]
Thanks for your inspiring work.

I have a question regarding the experimental setting of the paper.
In the paper:
> From the entire node set, we select a subset of nodes uniformly at random as the “seen” nodes with installed sensors. Inference and loss calculation is performed only on the unseen nodes.

However, in the dataset file, it seems you only use seen nodes to optimize the network.
Then, only unseen nodes are utilized to evaluate the performance. (i.e., you feed historical signals of unseen nodes into the network, and the model will forecast their readings).
This is an inductive setting. However, if those nodes are unseen. Why should we have their historical signals?
The right setting to align with your motivation is to use _historical readings of seen nodes_ to predict _readings of unseen nodes_ during testing.

Then, even in the file, seems you use unseen nodes to train the network.
https://github.com/frigategnn/Frigate/blob/9d1918ea95ab816967e415d0abe893808fce8b73/utils/data_utils.py#L100C33-L100C33

Looking forward to your reply~

**Comment by frigategnn** [comment]
We do exactly what you are saying: use _historical readings of seen nodes_ to predict _readings of unseen nodes_ during testing.

The lines that you have pointed out from `data_utils.py` does take in `unseen_node_ids`, however, they are used to "zero" out the historical data of unseen nodes on the fly. Since the dataset is z-score normalized before, zeroing out the data means setting it to $\frac{0-\mu}{\sigma}=-\mu/\sigma$, which is what line 26 in `data_utils.py` does. And that is the only place where `unseen_node_ids` is used.

Hope that clears it.
